"""
sensitivity_with_quality.py — Crop Area + Pixel Quality Sensitivity Analysis
=============================================================================
Purpose:
  Extends Week_10's sensitivity analysis by adding pixel-overlap quality
  as an additional dimension. This proves that the temporal grouping
  results are robust to both crop area thresholds AND district quality.

Method:
  1. For each crop area threshold (0%, 10%, 25%, 50%):
     a. Run with ALL districts
     b. Run with only High/Medium quality districts
  2. Compare the temporal grouping strength (avg inter-district correlation)
  3. If both tracks converge to the same conclusion → centroid method validated

Outputs:
  - zambia_sensitivity_comparison.csv — full results table
  - zambia_sensitivity_figure.png — 2x2 comparison panel
"""

import os
import sys
import numpy as np
import pandas as pd
import geopandas as gpd
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
from pathlib import Path
import warnings

sys.path.insert(0, str(Path(__file__).resolve().parents[2]))
from ssi_lib import compute_zscore_ssi, aggregate_annual_drought_days
warnings.filterwarnings("ignore")

# ---------------------------------------------------------------------------
# CONFIG
# ---------------------------------------------------------------------------
PROJECT_ROOT = Path(__file__).resolve().parents[2]
DATA_DIR = PROJECT_ROOT / "data"
# This points to the outputs folder created by your Week 11 run
OUTPUT_DIR = PROJECT_ROOT / "dissertation_work" / "outputs" / "sensitivity_with_quality"
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

# FIXED: Removed the extra subfolder 'africa-agricultural-domain-2019'
GADM_PATH = DATA_DIR / "africa_agricultural_domain_2019.shp"

# FIXED: Path to the ERA5 data
ERA5_PATH = DATA_DIR / "Africa_Agri_districts_ERA5_LAND_DAILY_AGGR_2000_2026_timeseries.csv"

# FIXED: Points to the quality file generated by your previous successful run
QUALITY_PATH = PROJECT_ROOT / "dissertation_work" / "outputs" / "overlap_analysis" / "districts_with_quality.geojson"

SSI_THRESHOLD = -1.0
CROP_AREA_THRESHOLDS = [0, 10, 25, 50]


# ===========================================================================
# STEP 1: Load data
# ===========================================================================
def load_data():
    """
    Load Zambia districts with crop_pct + quality metrics + ERA5 data.

    Returns
    -------
    zmb_districts : gpd.GeoDataFrame — 70 districts with crop_pct, quality_class
    zmb_era5     : pd.DataFrame — daily ERA5 soil moisture for Zambia
    """
    print("=" * 70)
    print("STEP 1: Loading Zambia data with quality metrics")
    print("=" * 70)

    # Load districts with quality metrics
    if QUALITY_PATH.exists():
        zmb = gpd.read_file(QUALITY_PATH)
        print(f"  Loaded quality metrics from: {QUALITY_PATH}")
    else:
        print("  ⚠ Quality file not found. Loading from GADM shapefile instead.")
        gdf = gpd.read_file(GADM_PATH)
        gdf["ADM_NAME"] = gdf["ADM_NAME"].astype(str).str.strip().str.upper()
        zmb = gdf[gdf["ISO3"] == "ZMB"].copy()
        zmb["quality_class"] = "Unknown"
        zmb["pct_full_pixels"] = np.nan

    print(f"  Zambia districts: {len(zmb)}")
    print(f"  Quality distribution: {zmb['quality_class'].value_counts().to_dict()}")
    print(f"  Crop area range: {zmb['crop_pct'].min():.1f}–{zmb['crop_pct'].max():.1f}%")

    # Load ERA5 (only Zambia districts)
    print(f"\n  Loading ERA5 data …")
    zmb_names = set(zmb["ADM_NAME"])
    dtype = {"year": "int16", "month": "int8", "day": "int8", "doy": "int16",
             "volumetric_soil_water_layer_2": "float32"}
    chunks = []
    for chunk in pd.read_csv(ERA5_PATH, dtype=dtype, chunksize=500000):
        chunk["feature_id"] = chunk["feature_id"].astype(str).str.strip().str.upper()
        chunk = chunk[chunk["feature_id"].isin(zmb_names)]
        if not chunk.empty:
            chunks.append(chunk)
    zmb_era5 = pd.concat(chunks, ignore_index=True) if chunks else pd.DataFrame()
    print(f"  ERA5 rows for Zambia: {len(zmb_era5):,}")
    print(f"  Year range: {zmb_era5['year'].min()}–{zmb_era5['year'].max()}")

    return zmb, zmb_era5


# ===========================================================================
# STEP 2: Compute SSI and annual drought days
# ===========================================================================
def compute_ssi(zmb_era5):
    """
    Compute SSI via z-score method and aggregate to annual drought days.

    Uses Jan-Apr risk window (matching Week_10's Zambia-specific window).

    Returns
    -------
    df_annual : pd.DataFrame [feature_id, year, Drought_Days]
    """
    print("\n" + "=" * 70)
    print("STEP 2: Computing SSI and annual drought days")
    print("=" * 70)

    if zmb_era5.empty:
        print("  ⚠ No ERA5 data")
        return pd.DataFrame()

    df = compute_zscore_ssi(zmb_era5)

    # Risk window: Jan-Apr (Zambia's main rainy/growing season, per Week_10)
    df_risk = df[df["month"].between(1, 4)].copy()

    annual = aggregate_annual_drought_days(df_risk, ssi_threshold=SSI_THRESHOLD)

    print(f"  Districts with SSI: {annual['feature_id'].nunique()}")
    print(f"  Years: {annual['year'].min()}–{annual['year'].max()}")
    print(f"  Mean drought days: {annual['Drought_Days'].mean():.1f}")

    return annual


# ===========================================================================
# STEP 3: Run sensitivity analysis
# ===========================================================================
def get_group_synchronicity(pivot_table, district_list):
    """
    Calculate the average pairwise Pearson correlation between districts.

    This is the "temporal grouping strength" metric from Week_10.

    Parameters
    ----------
    pivot_table : pd.DataFrame (years × districts, values = drought days)
    district_list : list of district names to include

    Returns
    -------
    float : mean pairwise correlation (r)
    """
    available = [d for d in district_list if d in pivot_table.columns]
    if len(available) < 2:
        return np.nan

    corr = pivot_table[available].corr()
    upper = corr.where(np.triu(np.ones(corr.shape), k=1).astype(bool))
    return upper.stack().mean()


def run_sensitivity(annual_df, zmb_districts, label_suffix=""):
    """
    Run the full sensitivity analysis across crop area thresholds.

    Parameters
    ----------
    annual_df : pd.DataFrame with [feature_id, year, Drought_Days]
    zmb_districts : gpd.GeoDataFrame with crop_pct and quality_class
    label_suffix : str — appended to threshold labels for clarity

    Returns
    -------
    pd.DataFrame with columns: [threshold, n_districts, avg_correlation]
    """
    pivot = annual_df.pivot_table(
        index="year", columns="feature_id", values="Drought_Days"
    )

    results = []
    for t in CROP_AREA_THRESHOLDS:
        valid = zmb_districts[zmb_districts["crop_pct"] >= t]["ADM_NAME"].unique()
        avg_corr = get_group_synchronicity(pivot, valid)
        results.append({
            "threshold": f"{t}%{label_suffix}",
            "threshold_value": t,
            "n_districts": len(valid),
            "avg_correlation": avg_corr,
        })
        print(f"    {t}%{label_suffix}: {len(valid):>2} districts, "
              f"avg r = {avg_corr:.4f}")

    return pd.DataFrame(results)


# ===========================================================================
# STEP 4: Main analysis
# ===========================================================================
def main():
    print("=" * 70)
    print("SENSITIVITY ANALYSIS — Crop Area + Pixel Quality")
    print("=" * 70)
    print("\nQuestion: Does filtering by pixel-overlap quality change the")
    print("temporal grouping outcomes at different crop area thresholds?")

    # Step 1: Load data
    zmb, zmb_era5 = load_data()

    # Step 2: Compute SSI
    annual = compute_ssi(zmb_era5)
    if annual.empty:
        print("❌ No data — aborting")
        return

    # Step 3: Run sensitivity — ALL districts
    print("\n" + "=" * 70)
    print("STEP 3A: Sensitivity — ALL districts")
    print("=" * 70)
    results_all = run_sensitivity(annual, zmb, label_suffix=" (all)")

    # Step 4: Run sensitivity — HIGH/MEDIUM quality only
    print("\n" + "=" * 70)
    print("STEP 3B: Sensitivity — HIGH/MEDIUM quality only")
    print("=" * 70)
    zmb_clean = zmb[zmb["quality_class"].isin(["High", "Medium"])].copy()
    print(f"  Clean districts: {len(zmb_clean)} / {len(zmb)}")
    results_clean = run_sensitivity(annual, zmb_clean, label_suffix=" (clean)")

    # Step 5: Combine and save
    print("\n" + "=" * 70)
    print("STEP 4: Comparison results")
    print("=" * 70)
    combined = pd.concat([results_all, results_clean], ignore_index=True)
    combined.to_csv(OUTPUT_DIR / "zambia_sensitivity_comparison.csv", index=False)
    print(f"\n  Results saved: zambia_sensitivity_comparison.csv")
    print(combined.to_string(index=False))

    # Step 6: Generate figure
    print("\n" + "=" * 70)
    print("STEP 5: Generating comparison figure")
    print("=" * 70)

    fig, axes = plt.subplots(1, 3, figsize=(16, 5))

    # Panel 1: District count by threshold
    ax = axes[0]
    x = np.arange(len(CROP_AREA_THRESHOLDS))
    w = 0.3
    ax.bar(x - w/2, results_all["n_districts"], w,
           label="All districts", color="steelblue", alpha=0.8)
    ax.bar(x + w/2, results_clean["n_districts"], w,
           label="Clean districts", color="darkorange", alpha=0.8)
    ax.set_xticks(x)
    ax.set_xticklabels([f"{t}%" for t in CROP_AREA_THRESHOLDS])
    ax.set_xlabel("Crop area threshold")
    ax.set_ylabel("Number of districts")
    ax.set_title("District pool size")
    ax.legend(fontsize=9)
    ax.grid(axis="y", alpha=0.3)

    # Panel 2: Correlation by threshold
    ax = axes[1]
    ax.plot(CROP_AREA_THRESHOLDS, results_all["avg_correlation"],
            "o-", color="steelblue", linewidth=2.5, label="All districts")
    ax.plot(CROP_AREA_THRESHOLDS, results_clean["avg_correlation"],
            "s--", color="darkorange", linewidth=2.5, label="Clean districts")
    ax.set_xlabel("Crop area threshold (%)")
    ax.set_ylabel("Avg inter-district correlation (r)")
    ax.set_title("Temporal grouping strength")
    ax.set_ylim(0, 1)
    ax.legend(fontsize=9)
    ax.grid(True, alpha=0.3)

    # Annotate convergence
    max_diff = abs(results_all["avg_correlation"] - results_clean["avg_correlation"]).max()
    ax.text(0.5, 0.05,
            f"Max diff between tracks: {max_diff:.3f} r",
            transform=ax.transAxes, fontsize=10,
            bbox=dict(boxstyle="round", facecolor="white", alpha=0.8),
            ha="center")

    # Panel 3: Quality distribution
    ax = axes[2]
    if "quality_class" in zmb.columns:
        counts = zmb["quality_class"].value_counts()
        colors = {"High": "#1b9e77", "Medium": "#d95f02", "Low": "#e7298a"}
        bars = ax.bar(
            ["High", "Medium", "Low"],
            [counts.get("High", 0), counts.get("Medium", 0), counts.get("Low", 0)],
            color=[colors.get(c, "gray") for c in ["High", "Medium", "Low"]]
        )
        for bar, count in zip(bars, [counts.get("High", 0), counts.get("Medium", 0), counts.get("Low", 0)]):
            ax.text(bar.get_x() + bar.get_width()/2., bar.get_height(),
                    str(count), ha="center", va="bottom", fontweight="bold")
        ax.set_xlabel("Pixel-overlap quality class")
        ax.set_ylabel("Number of districts")
        ax.set_title("Zambia quality distribution")

    plt.suptitle(
        "Sensitivity Analysis: Crop Area Thresholds × Pixel-Overlap Quality",
        fontweight="bold", fontsize=13, y=1.02
    )
    plt.tight_layout()
    fig.savefig(OUTPUT_DIR / "zambia_sensitivity_figure.png",
                dpi=200, bbox_inches="tight")
    plt.close()
    print(f"  Saved: zambia_sensitivity_figure.png")

    # Final interpretation
    print("\n" + "=" * 70)
    print("INTERPRETATION")
    print("=" * 70)
    conv = (abs(results_all["avg_correlation"].values -
                results_clean["avg_correlation"].values) < 0.05).all()
    if conv:
        print(f"✅ The two tracks converge (max diff = {max_diff:.3f} r).")
        print("   Conclusion: Quality filtering does not change the")
        print("   temporal grouping outcomes. The centroid method is validated.")
    else:
        print(f"⚠ The two tracks diverge (max diff = {max_diff:.3f} r).")
        print("   Consider using weighted GEOGLAM assignment for low-quality districts.")

    print(f"\n  All outputs: {OUTPUT_DIR}")
    print("\n✅ SENSITIVITY ANALYSIS COMPLETE")


if __name__ == "__main__":
    main()
